const STRATEGIES = [
  {
    id: "gig-micro-credit",
    num: "01",
    name: "Gig Micro-Credit Line",
    categories: ["micro", "gig"],
    year: "2026",
    desc: "Revolving $50–$2,000 credit line attached to gig platform earnings, with repayment auto-deducted as a percentage of each payout.",
    cagr: "34%",
    marketCapture: "$12.4B",
    breakeven: "1.8 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [1.2, 3.8, 6.9, 9.7, 12.4],
    useCase: "Gig workers (65M+ in the US by 2026) lack access to traditional credit due to irregular income. This product attaches directly to platform payouts — no credit score required — solving the last-mile credit access problem for America's gig workforce.",
    businessValue: [
      "Addresses 65M+ unbanked/underbanked gig workers in the US",
      "Zero physical branch costs — fully API-delivered",
      "Default rate 60% lower than traditional unsecured personal loans",
      "Platform partnership revenue: 1.2% origination fee per advance",
      "Data flywheel: earnings data improves AI pricing over time",
      "Cross-sell bridge to savings products and insurance"
    ],
    aiRole: "Earnings forecasting engine predicts 14-day income trajectory; sets repayment % that guarantees no negative payout event."
  },
  {
    id: "instant-trade-credit",
    num: "02",
    name: "Instant Trade Credit (ITC)",
    categories: ["micro", "gig"],
    year: "2026",
    desc: "$100–$5,000 micro-business loan disbursed in 90 seconds via open-banking verification. No collateral, no credit history required.",
    cagr: "41%",
    marketCapture: "$18.7B",
    breakeven: "1.5 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [1.8, 5.2, 9.8, 14.3, 18.7],
    useCase: "30M+ micro-businesses (food vendors, market sellers, micro-retailers) operate with net-30 to net-60 payment gaps but need inventory funding today. ITC bridges this gap in 90 seconds — replacing predatory payday-style products.",
    businessValue: [
      "30M micro-businesses addressable in the US alone",
      "APR pricing: 12–28% based on risk tier — competitive but profitable",
      "90-second disbursement vs. 3–5 day bank alternatives",
      "Bank partnership channel: white-label for community banks",
      "Reduction in predatory lending market: regulatory goodwill",
      "International expansion: same infrastructure serves 200+ markets"
    ],
    aiRole: "Cash-flow pattern scorer evaluates 90-day transaction history to compute repayment probability in milliseconds."
  },
  {
    id: "community-lending-circle",
    num: "03",
    name: "Community Lending Circle",
    categories: ["micro", "savings"],
    year: "2026",
    desc: "Cooperative micro-lending where 8–20 community members pool monthly contributions. Each member receives the full pot in rotation, AI-managed.",
    cagr: "28%",
    marketCapture: "$6.1B",
    breakeven: "2.2 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [0.6, 1.8, 3.4, 4.9, 6.1],
    useCase: "Digitizes ROSCA (Rotating Savings and Credit Associations) — a financial practice used by 1B+ people globally, particularly in immigrant and underbanked communities. Makes it bank-eligible, insured, and AI-risk-managed.",
    businessValue: [
      "Tap into $1T+ informal ROSCA market globally",
      "Community trust drives viral adoption — low CAC",
      "Platform fee: 0.5% of pool per rotation cycle",
      "Zero loan losses when AI-matched groups perform — first-loss absorbed by reserve",
      "CRA credit qualifying for bank partners",
      "Bridges informal economy into formal financial system"
    ],
    aiRole: "Group credit optimizer screens members for compatibility, predicts sequencing to minimize default exposure, adjusts pool size dynamically."
  },
  {
    id: "fuel-advance",
    num: "04",
    name: "Fuel Advance Micro-Loan",
    categories: ["micro", "gig", "energy"],
    year: "2026",
    desc: "$25–$300 instant advance for fuel costs, triggered when AI detects earnings-to-fuel-cost ratio at risk. Auto-repaid from next 3–5 payouts.",
    cagr: "47%",
    marketCapture: "$4.8B",
    breakeven: "1.2 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [0.5, 1.4, 2.6, 3.8, 4.8],
    useCase: "Gas shortage + gig economy = a new crisis: delivery drivers stranding mid-shift because they can't afford to fill up. The Fuel Advance triggers automatically — before the driver realizes they're stuck — keeping platform uptime high and workers earning.",
    businessValue: [
      "Direct revenue: 3–5% fee on each advance",
      "Platform benefit: reduces driver downtime and churn by ~22%",
      "Uber/DoorDash partnership: white-label embedded in driver apps",
      "Avg advance: $85 · avg fee: $4.25 · 56M advances/yr at scale",
      "Data: fuel spend data informs gas hedge savings product",
      "Zero incremental cost — uses existing earnings data"
    ],
    aiRole: "Real-time trigger detection monitors GPS work-session and platform earnings data; pre-approves before driver asks."
  },
  {
    id: "harvest-advance",
    num: "05",
    name: "Harvest Advance (Ag Micro-Loan)",
    categories: ["micro", "farming"],
    year: "2027",
    desc: "Seasonal $200–$10,000 credit for small farmers, disbursed at planting and repaid at harvest. Pricing adjusts to AI-forecast yield and weather risk.",
    cagr: "31%",
    marketCapture: "$9.3B",
    breakeven: "2.5 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [0.9, 2.7, 5.1, 7.4, 9.3],
    useCase: "2M+ small US farms lack access to affordable seasonal credit. Traditional ag loans require 90-day underwriting. Harvest Advance uses satellite imagery, weather models, and commodity prices to underwrite in hours — keeping family farms solvent through planting season.",
    businessValue: [
      "2M US small farms · $230B annual operating credit need",
      "USDA partnership for guarantee programs reduces credit risk",
      "Linked crop insurance at disbursement creates bundled revenue",
      "APR: 8–18% seasonal — significantly below ag credit card rates",
      "International: same model applies to 500M+ smallholders globally",
      "ESG premium: sustainable farming practices lower pricing"
    ],
    aiRole: "Yield and repayment probability engine integrates USDA data, weather models, and satellite crop health imagery."
  },
  {
    id: "adaptive-round-up",
    num: "06",
    name: "Adaptive Round-Up Savings (ARS)",
    categories: ["savings", "ai"],
    year: "2026",
    desc: "AI determines optimal round-up per transaction ($0.10–$5.00) based on remaining monthly budget. Funds auto-invest in inflation-beating instruments.",
    cagr: "38%",
    marketCapture: "$21.5B",
    breakeven: "1.6 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [2.1, 6.4, 11.8, 17.2, 21.5],
    useCase: "Static round-up apps (Acorns, Chime) round up by $0.50 blindly, causing overdrafts. ARS intelligently calibrates savings amount to what the customer can actually afford that day — making savings frictionless for 70M+ Americans who currently save nothing.",
    businessValue: [
      "AUM fee: 0.25% annually on invested round-up balances",
      "Average ARS user saves $1,840/yr at scale vs $0 previously",
      "Overdraft elimination: saves bank $38/overdraft event reversed",
      "Data: spending patterns power credit underwriting across other products",
      "Bank partner license: $4/active user/month",
      "Pathway to full advisory relationship — LTV multiplier of 4.2x"
    ],
    aiRole: "Budget-aware savings optimizer determines round-up size in real time and routes funds to highest real-yield instrument available."
  },
  {
    id: "goal-linked-bond",
    num: "07",
    name: "Goal-Linked Savings Bond (GLSB)",
    categories: ["savings", "ai"],
    year: "2027",
    desc: "Retail savings product where yield increases as customer progresses toward a declared goal. Yield steps from 3% → 4.5% → 6% at milestone thresholds.",
    cagr: "29%",
    marketCapture: "$14.2B",
    breakeven: "2.1 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [1.4, 4.1, 7.8, 11.3, 14.2],
    useCase: "80% of Americans fail to achieve savings goals due to lack of progressive incentive. GLSB turns saving into a game with real financial rewards — higher yields for consistent behavior. Targets the $4.2T in low-yield savings accounts earning below inflation.",
    businessValue: [
      "NIM spread: bank earns margin on goal-locked deposits",
      "Behavioral lock-in reduces deposit churn by 65%",
      "Employer benefit program: company tops up yield for employees",
      "Emergency fund mandate integration with insurance partners",
      "Regulatory benefit: CFPB safe harbor for goal-based products",
      "Cross-sell insurance and investment at goal completion"
    ],
    aiRole: "Goal-progress tracker and yield trigger monitors linked accounts, verifies milestone thresholds, auto-upgrades yield tier."
  },
  {
    id: "gas-hedge-savings",
    num: "08",
    name: "Gas Hedge Savings Account",
    categories: ["savings", "energy"],
    year: "2027",
    desc: "Savings account earning cash yield plus a fuel hedge. When gas prices spike above personal baseline, the hedge pays a fuel credit — locking in personal fuel price.",
    cagr: "52%",
    marketCapture: "$8.6B",
    breakeven: "1.4 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [0.8, 2.5, 4.9, 7.0, 8.6],
    useCase: "Gas shortage creates massive consumer anxiety around fuel price volatility. The Gas Hedge Savings Account gives everyday Americans access to commodity hedging — previously only available to airlines and trucking companies — converting a pain point into a banking relationship.",
    businessValue: [
      "Hedge fee revenue: 0.8% of deposit balance annually",
      "Unique product — no comparable retail competitor in 2027",
      "Drives new-to-bank acquisition: 38% of signups are new customers",
      "Commodity trading desk revenue from pooled hedge execution",
      "Media/PR value: first bank to offer personal gas price hedging",
      "Insurance partnership: pairs with auto insurance telematics"
    ],
    aiRole: "Personal fuel baseline engine learns historical fuel spend, computes individual hedge ratio, auto-executes micro-hedges in background."
  },
  {
    id: "skills-savings",
    num: "09",
    name: "Skills-Linked Savings Account (SLSA)",
    categories: ["savings", "gig"],
    year: "2027",
    desc: "Savings account where completing verified online certifications earns bonus yield — up to 1.5% extra APY per credential earned per year.",
    cagr: "33%",
    marketCapture: "$7.8B",
    breakeven: "2.0 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [0.8, 2.3, 4.4, 6.3, 7.8],
    useCase: "Unemployment from automation drives massive demand for retraining. SLSA aligns financial incentives with career development — making upskilling financially rewarding at the account level. Employers match yield as a benefits program, replacing traditional tuition reimbursement.",
    businessValue: [
      "Employer benefit channel: $2B+ tuition reimbursement market disruption",
      "EdTech platform partnerships: Coursera, LinkedIn Learning, Udemy revenue share",
      "Reduced credit risk: skilled workers have 40% lower default rates",
      "Government incentive alignment: matches workforce development grants",
      "Data: skills data improves credit pricing and product cross-sell",
      "Retention tool for employer-sponsored programs"
    ],
    aiRole: "Credential verifier and yield calculator integrates with Coursera, LinkedIn Learning, and certification bodies to verify and apply yield bonuses."
  },
  {
    id: "family-resilience-vault",
    num: "10",
    name: "Family Resilience Vault",
    categories: ["savings", "ai"],
    year: "2028",
    desc: "Multi-member savings product for up to 6 household members. Pools emergency fund while maintaining individual sub-accounts. AI allocates contributions per risk profile.",
    cagr: "26%",
    marketCapture: "$11.4B",
    breakeven: "2.4 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [1.1, 3.3, 6.1, 9.0, 11.4],
    useCase: "Rising expenses and unemployment force households to function as economic units, not individuals. The Family Resilience Vault treats the household as the financial unit of analysis — pooling risk, optimizing contributions, and surfacing early warning signals before financial crisis hits.",
    businessValue: [
      "Household accounts: 6x the AUM of individual accounts",
      "Low churn: family financial products have 8-year avg. retention",
      "Insurance partner integration: family coverage at vault milestone",
      "Employer family benefit: companies offer vault contributions as perk",
      "Referral flywheel: one member joins, recruits 5 more",
      "Social safety net augmentation: reduces welfare claims"
    ],
    aiRole: "Household financial planner models each member's income volatility, optimizes contributions, surfaces early warning signals."
  },
  {
    id: "ai-credit-decisioning",
    num: "11",
    name: "AI Credit Decisioning Engine",
    categories: ["ai", "micro"],
    year: "2026",
    desc: "Real-time loan approvals using ML trained on 500+ behavioral and financial signals. Replaces FICO-only gating. Reduces underwriting costs by 40%.",
    cagr: "44%",
    marketCapture: "$32.8B",
    breakeven: "1.3 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [3.2, 9.6, 18.4, 26.9, 32.8],
    useCase: "45M Americans are credit-invisible — FICO can't score them. AI credit decisioning uses 500+ alternative signals (rent payments, utility bills, subscription history) to safely extend credit to thin-file applicants, expanding the addressable lending market by ~$280B.",
    businessValue: [
      "License fee to banks: $0.45 per decision at scale",
      "40% reduction in underwriting cost vs human review",
      "18% lower default rate vs traditional FICO-only models",
      "Regulatory: CFPB-compliant explainability built in",
      "Expands TAM by $280B of previously unserviceable borrowers",
      "Network effect: more decisions = smarter model = lower risk"
    ],
    aiRole: "Core decision layer — multi-modal ML evaluates 500+ signals and produces CFPB-compliant explainable credit decisions in <200ms."
  },
  {
    id: "embedded-mobility-wallet",
    num: "12",
    name: "Embedded Mobility Wallet",
    categories: ["ai", "energy", "gig"],
    year: "2027",
    desc: "Financial product built into EVs and transit apps. Auto-calculates commute cost, suggests fuel vs. transit modes, pays tolls/fares from one AI-managed wallet.",
    cagr: "39%",
    marketCapture: "$16.2B",
    breakeven: "1.9 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [1.6, 4.8, 9.1, 13.2, 16.2],
    useCase: "Gas shortage forces 280M US commuters to rethink mobility. The Embedded Mobility Wallet becomes the financial layer for multimodal commuting — sitting inside the car OS, transit app, or rideshare platform — making it invisible, sticky, and high-frequency.",
    businessValue: [
      "OEM partnership (Ford, GM, Tesla): embedded in vehicle OS",
      "Transaction fee: 0.4% of every toll/transit/charging payment",
      "Float revenue on wallet balances: avg $340/user",
      "Mobility data: most valuable dataset for insurance + credit pricing",
      "Carbon credit generation from transit-mode-shift tracking",
      "Captive audience: daily financial touchpoint in the car"
    ],
    aiRole: "Route intelligence + auto-funding — predicts route costs 7 days ahead, suggests optimal transit mix, auto-tops wallet before funds deplete."
  },
  {
    id: "predictive-overdraft",
    num: "13",
    name: "Predictive Overdraft Prevention",
    categories: ["ai", "savings"],
    year: "2027",
    desc: "AI layer predicting overdraft risk 3–7 days ahead. Automatically moves funds, pauses subscriptions, or unlocks micro-credit — invisibly preventing overdraft fees.",
    cagr: "36%",
    marketCapture: "$9.1B",
    breakeven: "1.1 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [0.9, 2.7, 5.1, 7.4, 9.1],
    useCase: "US consumers pay $11B+ annually in overdraft fees — a regressive tax on the poor. Predictive Overdraft Prevention eliminates this by intervening invisibly 3–7 days before the event. Banks that adopt it turn a fee center into a trust-building retention product.",
    businessValue: [
      "Reduces $11B overdraft fee burden — massive PR and regulatory value",
      "Bank subscription fee: $4/user/month replacing fee revenue",
      "Reduces account closures caused by overdraft: saves $285/closed account",
      "Cross-sell: overdraft-prevented users open investment accounts at 3.4x rate",
      "Regulatory compliance: CFPB overdraft rules adherence",
      "Net promoter score impact: +34 NPS lift at partner banks"
    ],
    aiRole: "Cash-flow forecasting + auto-intervention — learns each customer's unique cash-flow fingerprint and intervenes invisibly."
  },
  {
    id: "bridge-fund",
    num: "14",
    name: "BRIDGE Impact Fund",
    categories: ["bridge", "farming", "energy"],
    year: "2026",
    desc: "US-domiciled impact fund deploying capital into infrastructure, farming, gig economy, and energy access globally. US investors earn 5.5–12% IRR with CRA credit.",
    cagr: "58%",
    marketCapture: "$47.3B",
    breakeven: "2.8 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [4.7, 14.1, 27.0, 38.4, 47.3],
    useCase: "US banks need CRA credit. Institutional investors need impact returns. Developing nations need infrastructure capital. The BRIDGE Fund creates a three-sided match — structuring global development projects as investable US financial products, with AI managing underwriting and monitoring at $25B scale.",
    businessValue: [
      "Management fee: 1.5% on $25B = $375M/yr at scale",
      "Carried interest: 20% above 8% hurdle rate on equity tranche",
      "Bank CRA compliance: replaces $180M in traditional CRA investments",
      "Government co-investment: OPIC/DFC partnership reduces risk",
      "Carbon credit generation: additional 80–180bps yield supplement",
      "15% domestic reserve recycled as US micro-loans and energy projects"
    ],
    aiRole: "Multi-agent LLM consensus (3-of-5 model agreement) screens 500+ projects across 60+ countries; allocates and rebalances quarterly."
  },
  {
    id: "personal-financial-os",
    num: "15",
    name: "Personal Financial OS",
    categories: ["ai", "savings"],
    year: "2030",
    desc: "Single AI-managed financial layer aggregating all accounts, liabilities, income, and goals. Autonomously executes optimal financial strategy 24/7 via multi-LLM consensus.",
    cagr: "61%",
    marketCapture: "$78.4B",
    breakeven: "3.1 yrs",
    cagrColor: "green",
    marketColor: "blue",
    breakevenColor: "amber",
    marketData: [7.8, 23.5, 45.0, 64.0, 78.4],
    useCase: "By 2030, AI capable of autonomous financial management is available but unstructured. The Personal Financial OS is the interface layer — a legally-structured, explainable AI agent that manages money the way a CFO manages a company, but for every household.",
    businessValue: [
      "Platform fee: $25/month per household × 100M target users = $30B ARR",
      "Replaces $80B+ in fragmented fintech subscriptions",
      "Data network: most comprehensive household financial dataset ever built",
      "B2B licensing: bank and employer channel at $8/user/month",
      "Regulatory moat: first-mover on explainable autonomous finance",
      "Cross-product revenue: orchestrates all other FinBridge products"
    ],
    aiRole: "Full-stack autonomous management — multi-LLM consensus architecture with specialized agents for credit, investment, insurance, and tax."
  }
];
